apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sbj7g92qs-python
  janus-idp.io/tekton: sbj7g92qs-python
  backstage.io/kubernetes-id: sbj7g92qs-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sbj7g92qs-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
