apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sbj7g92qs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sbj7g92qs-python 
  name: sbj7g92qs-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sbj7g92qs-python 
